export const ErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  CONFLICT: "CONFLICT",
  WISHLIST_ALREADY_EXISTS: "WISHLIST_ALREADY_EXISTS",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
